=begin
#PagerDuty API

#This document describes the PagerDuty REST APIs.  For guides and examples please visit our [Documentation.](https://developer.pagerduty.com/docs/get-started/getting-started/)  Our REST APIs are defined in OpenAPI v3.x. You can view the schema at [github.com/PagerDuty/api-schema](https://github.com/PagerDuty/api-schema).  Note that properties in some schemas have fields not shown by default such as `readOnly`, `format`, and `default`. Hover your cursor over the right column that looks like `optional+1` to see the full list of fields. 

The version of the OpenAPI document: 2.0.0
Contact: support@pagerduty.com
Generated by: https://openapi-generator.tech
Generator version: 7.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::AlertGroupingSettingsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AlertGroupingSettingsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::AlertGroupingSettingsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AlertGroupingSettingsApi' do
    it 'should create an instance of AlertGroupingSettingsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::AlertGroupingSettingsApi)
    end
  end

  # unit tests for delete_alert_grouping_setting
  # Delete an Alert Grouping Setting
  # Delete an existing Alert Grouping Setting.  The settings part of Alert Grouper service allows us to create Alert Grouping Settings and configs that are required to be used during grouping of the alerts.  Scoped OAuth requires: &#x60;services.write&#x60; 
  # @param accept The &#x60;Accept&#x60; header is used as a versioning header.
  # @param content_type 
  # @param id The ID of the resource.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_alert_grouping_setting test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_alert_grouping_setting
  # Get an Alert Grouping Setting
  # Get an existing Alert Grouping Setting.  The settings part of Alert Grouper service allows us to create Alert Grouping Settings and configs that are required to be used during grouping of the alerts.  Scoped OAuth requires: &#x60;services.read&#x60; 
  # @param accept The &#x60;Accept&#x60; header is used as a versioning header.
  # @param content_type 
  # @param id The ID of the resource.
  # @param [Hash] opts the optional parameters
  # @return [PostAlertGroupingSettingsRequest]
  describe 'get_alert_grouping_setting test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_alert_grouping_settings
  # List alert grouping settings
  # List all of your alert grouping settings including both single service settings and global content based settings.  The settings part of Alert Grouper service allows us to create Alert Grouping Settings and configs that are required to be used during grouping of the alerts.  Scoped OAuth requires: &#x60;services.read&#x60; 
  # @param accept The &#x60;Accept&#x60; header is used as a versioning header.
  # @param content_type 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :after Cursor to retrieve next page; only present if next page exists.
  # @option opts [String] :before Cursor to retrieve previous page; only present if not on first page.
  # @option opts [Boolean] :total By default the &#x60;total&#x60; field in pagination responses is set to &#x60;null&#x60; to provide the fastest possible response times. Set &#x60;total&#x60; to &#x60;true&#x60; for this field to be populated.  See our [Pagination Docs](https://developer.pagerduty.com/docs/rest-api-v2/pagination/) for more information. 
  # @option opts [Integer] :limit The number of results per page.
  # @option opts [Array<String>] :service_ids An array of service IDs. Only results related to these services will be returned.
  # @return [ListAlertGroupingSettings200Response]
  describe 'list_alert_grouping_settings test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for post_alert_grouping_settings
  # Create an Alert Grouping Setting
  # Create a new Alert Grouping Setting.  The settings part of Alert Grouper service allows us to create Alert Grouping Settings and configs that are required to be used during grouping of the alerts.  This endpoint will be used to create an instance of AlertGroupingSettings for either one service or many services that are in the alert group setting.  Scoped OAuth requires: &#x60;services.write&#x60; 
  # @param accept The &#x60;Accept&#x60; header is used as a versioning header.
  # @param content_type 
  # @param [Hash] opts the optional parameters
  # @option opts [PostAlertGroupingSettingsRequest] :post_alert_grouping_settings_request 
  # @return [PostAlertGroupingSettingsRequest]
  describe 'post_alert_grouping_settings test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for put_alert_grouping_setting
  # Update an Alert Grouping Setting
  # Update an Alert Grouping Setting.  The settings part of Alert Grouper service allows us to create Alert Grouping Settings and configs that are required to be used during grouping of the alerts.  if &#x60;services&#x60; are not provided in the request, then the existing services will not be removed from the setting.  Scoped OAuth requires: &#x60;services.write&#x60; 
  # @param accept The &#x60;Accept&#x60; header is used as a versioning header.
  # @param content_type 
  # @param id The ID of the resource.
  # @param [Hash] opts the optional parameters
  # @option opts [PostAlertGroupingSettingsRequest] :post_alert_grouping_settings_request 
  # @return [PostAlertGroupingSettingsRequest]
  describe 'put_alert_grouping_setting test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
