=begin
#PagerDuty API

#This document describes the PagerDuty REST APIs.  For guides and examples please visit our [Documentation.](https://developer.pagerduty.com/docs/get-started/getting-started/)  Our REST APIs are defined in OpenAPI v3.x. You can view the schema at [github.com/PagerDuty/api-schema](https://github.com/PagerDuty/api-schema).  Note that properties in some schemas have fields not shown by default such as `readOnly`, `format`, and `default`. Hover your cursor over the right column that looks like `optional+1` to see the full list of fields. 

The version of the OpenAPI document: 2.0.0
Contact: support@pagerduty.com
Generated by: https://openapi-generator.tech
Generator version: 7.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for PagerDutyOpenapiClient::BusinessServicesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BusinessServicesApi' do
  before do
    # run before each test
    @api_instance = PagerDutyOpenapiClient::BusinessServicesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BusinessServicesApi' do
    it 'should create an instance of BusinessServicesApi' do
      expect(@api_instance).to be_instance_of(PagerDutyOpenapiClient::BusinessServicesApi)
    end
  end

  # unit tests for create_business_service
  # Create a Business Service
  # Create a new Business Service.  Business services model capabilities that span multiple technical services and that may be owned by several different teams.  There is a limit of 5,000 business services per account. If the limit is reached, the API will respond with an error.  For more information see the [API Concepts Document](../../api-reference/ZG9jOjI3NDc5Nzc-api-concepts#business-services)  Scoped OAuth requires: &#x60;services.write&#x60; 
  # @param accept The &#x60;Accept&#x60; header is used as a versioning header.
  # @param content_type 
  # @param [Hash] opts the optional parameters
  # @option opts [CreateBusinessServiceRequest] :create_business_service_request 
  # @return [CreateBusinessService200Response]
  describe 'create_business_service test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_business_service_account_subscription
  # Create Business Service Account Subscription
  # Subscribe your Account to a Business Service.  Scoped OAuth requires: &#x60;subscribers.write&#x60; 
  # @param accept The &#x60;Accept&#x60; header is used as a versioning header.
  # @param id The ID of the resource.
  # @param [Hash] opts the optional parameters
  # @return [CreateBusinessServiceAccountSubscription200Response]
  describe 'create_business_service_account_subscription test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_business_service_notification_subscribers
  # Create Business Service Subscribers
  # Subscribe the given entities to the given Business Service.  Scoped OAuth requires: &#x60;subscribers.write&#x60; 
  # @param accept The &#x60;Accept&#x60; header is used as a versioning header.
  # @param id The ID of the resource.
  # @param [Hash] opts the optional parameters
  # @option opts [CreateBusinessServiceNotificationSubscribersRequest] :create_business_service_notification_subscribers_request The entities to subscribe.
  # @return [CreateBusinessServiceNotificationSubscribers200Response]
  describe 'create_business_service_notification_subscribers test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_business_service
  # Delete a Business Service
  # Delete an existing Business Service.  Once the service is deleted, it will not be accessible from the web UI and new incidents won&#39;t be able to be created for this service.  Business services model capabilities that span multiple technical services and that may be owned by several different teams.  For more information see the [API Concepts Document](../../api-reference/ZG9jOjI3NDc5Nzc-api-concepts#business-services)  Scoped OAuth requires: &#x60;services.write&#x60; 
  # @param accept The &#x60;Accept&#x60; header is used as a versioning header.
  # @param content_type 
  # @param id The ID of the resource.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_business_service test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_business_service_priority_thresholds
  # Deletes the account-level priority threshold for Business Service impact
  # Clears the Priority Threshold for the account.  If the priority threshold is cleared, any Incident with a Priority set will be able to impact Business Services. Scoped OAuth requires: &#x60;services.write&#x60; 
  # @param accept The &#x60;Accept&#x60; header is used as a versioning header.
  # @param x_early_access This header indicates that this API endpoint is __UNDER CONSTRUCTION__ and may change at any time. You __MUST__ pass in this header with the value &#x60;business-impact-early-access&#x60;. Do not use this endpoint in production, as it may change!
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_business_service_priority_thresholds test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_business_service
  # Get a Business Service
  # Get details about an existing Business Service.  Business services model capabilities that span multiple technical services and that may be owned by several different teams.  For more information see the [API Concepts Document](../../api-reference/ZG9jOjI3NDc5Nzc-api-concepts#business-services)  Scoped OAuth requires: &#x60;services.read&#x60; 
  # @param accept The &#x60;Accept&#x60; header is used as a versioning header.
  # @param content_type 
  # @param id The ID of the resource.
  # @param [Hash] opts the optional parameters
  # @return [CreateBusinessService200Response]
  describe 'get_business_service test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_business_service_impacts
  # List Business Services sorted by impacted status
  # Retrieve a list top-level Business Services sorted by highest Impact with &#x60;status&#x60; included. When called without the &#x60;ids[]&#x60; parameter, this endpoint does not return an exhaustive list of Business Services but rather provides access to the most impacted up to the limit of 200.  The returned Business Services are sorted first by Impact, secondarily by most recently impacted, and finally by name.  To get impact information about a specific set of Business Services, use the &#x60;ids[]&#x60; parameter. Scoped OAuth requires: &#x60;services.read&#x60; 
  # @param accept The &#x60;Accept&#x60; header is used as a versioning header.
  # @param x_early_access This header indicates that this API endpoint is __UNDER CONSTRUCTION__ and may change at any time. You __MUST__ pass in this header with the value &#x60;business-impact-early-access&#x60;. Do not use this endpoint in production, as it may change!
  # @param [Hash] opts the optional parameters
  # @option opts [String] :additional_fields Provides access to additional fields such as highest priority per business service and total impacted count
  # @option opts [String] :ids The IDs of the resources.
  # @return [GetBusinessServiceSupportingServiceImpacts200Response]
  describe 'get_business_service_impacts test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_business_service_priority_thresholds
  # Get the global priority threshold for a Business Service to be considered impacted by an Incident
  # Retrieves the priority threshold information for an account.  Currently, there is a &#x60;global_threshold&#x60; that can be set for the account.  Incidents that have a priority meeting or exceeding this threshold will be considered impacting on any Business Service that depends on the Service to which the Incident belongs. Scoped OAuth requires: &#x60;services.read&#x60; 
  # @param accept The &#x60;Accept&#x60; header is used as a versioning header.
  # @param x_early_access This header indicates that this API endpoint is __UNDER CONSTRUCTION__ and may change at any time. You __MUST__ pass in this header with the value &#x60;business-impact-early-access&#x60;. Do not use this endpoint in production, as it may change!
  # @param [Hash] opts the optional parameters
  # @return [GetBusinessServicePriorityThresholds200Response]
  describe 'get_business_service_priority_thresholds test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_business_service_subscribers
  # List Business Service Subscribers
  # Retrieve a list of Notification Subscribers on the Business Service.  &lt;!-- theme: warning --&gt; &gt; Users must be added through &#x60;POST /business_services/{id}/subscribers&#x60; to be returned from this endpoint. Scoped OAuth requires: &#x60;subscribers.read&#x60; 
  # @param accept The &#x60;Accept&#x60; header is used as a versioning header.
  # @param id The ID of the resource.
  # @param [Hash] opts the optional parameters
  # @return [GetBusinessServiceSubscribers200Response]
  describe 'get_business_service_subscribers test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_business_service_supporting_service_impacts
  # List the supporting Business Services for the given Business Service Id, sorted by impacted status.
  # Retrieve of Business Services that support the given Business Service sorted by highest Impact with &#x60;status&#x60; included. This endpoint does not return an exhaustive list of Business Services but rather provides access to the most impacted up to the limit of 200.  The returned Business Services are sorted first by Impact, secondarily by most recently impacted, and finally by name.  To get impact information about a specific set of Business Services, use the &#x60;ids[]&#x60; parameter on the &#x60;/business_services/impacts&#x60; endpoint. Scoped OAuth requires: &#x60;services.read&#x60; 
  # @param accept The &#x60;Accept&#x60; header is used as a versioning header.
  # @param id The ID of the resource.
  # @param x_early_access This header indicates that this API endpoint is __UNDER CONSTRUCTION__ and may change at any time. You __MUST__ pass in this header with the value &#x60;business-impact-early-access&#x60;. Do not use this endpoint in production, as it may change!
  # @param [Hash] opts the optional parameters
  # @option opts [String] :additional_fields Provides access to additional fields such as highest priority per business service and total impacted count
  # @option opts [String] :ids The IDs of the resources.
  # @return [GetBusinessServiceSupportingServiceImpacts200Response]
  describe 'get_business_service_supporting_service_impacts test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_business_service_top_level_impactors
  # List Impactors affecting Business Services
  # Retrieve a list of Impactors for the top-level Business Services on the account. Impactors are currently limited to Incidents.  This endpoint does not return an exhaustive list of Impactors but rather provides access to the highest priority Impactors for the Business Services in question up to the limit of 200.  To get Impactors for a specific set of Business Services, use the &#x60;ids[]&#x60; parameter.  The returned Impactors are sorted first by priority and secondarily by their creation date. Scoped OAuth requires: &#x60;services.read&#x60; 
  # @param accept The &#x60;Accept&#x60; header is used as a versioning header.
  # @param x_early_access This header indicates that this API endpoint is __UNDER CONSTRUCTION__ and may change at any time. You __MUST__ pass in this header with the value &#x60;business-impact-early-access&#x60;. Do not use this endpoint in production, as it may change!
  # @param [Hash] opts the optional parameters
  # @option opts [String] :ids The IDs of the resources.
  # @return [GetBusinessServiceTopLevelImpactors200Response]
  describe 'get_business_service_top_level_impactors test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_business_services
  # List Business Services
  # List existing Business Services.  Business services model capabilities that span multiple technical services and that may be owned by several different teams.  For more information see the [API Concepts Document](../../api-reference/ZG9jOjI3NDc5Nzc-api-concepts#business-services)  Scoped OAuth requires: &#x60;services.read&#x60; 
  # @param accept The &#x60;Accept&#x60; header is used as a versioning header.
  # @param content_type 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit The number of results per page.
  # @option opts [Integer] :offset Offset to start pagination search results.
  # @option opts [Boolean] :total By default the &#x60;total&#x60; field in pagination responses is set to &#x60;null&#x60; to provide the fastest possible response times. Set &#x60;total&#x60; to &#x60;true&#x60; for this field to be populated.  See our [Pagination Docs](https://developer.pagerduty.com/docs/rest-api-v2/pagination/) for more information. 
  # @return [ListBusinessServices200Response]
  describe 'list_business_services test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for put_business_service_priority_thresholds
  # Set the Account-level priority threshold for Business Service impact.
  # Set the Account-level priority threshold for Business Service. Scoped OAuth requires: &#x60;services.write&#x60; 
  # @param accept The &#x60;Accept&#x60; header is used as a versioning header.
  # @param x_early_access This header indicates that this API endpoint is __UNDER CONSTRUCTION__ and may change at any time. You __MUST__ pass in this header with the value &#x60;business-impact-early-access&#x60;. Do not use this endpoint in production, as it may change!
  # @param [Hash] opts the optional parameters
  # @option opts [PutBusinessServicePriorityThresholdsRequest] :put_business_service_priority_thresholds_request Set the &#x60;id&#x60; and &#x60;order&#x60; of the global Priority Threshold. These values can be obtained by calling the &#x60;/priorities&#x60; endpoint.  Once set, Incidents must be at or above the specified level in order to impact Business Services.  An exception to this rule is if the Incident has been added to the incident directly using the &#x60;PUT /incidents/{id}/business_services/{business_service_id}/impacts&#x60; endpoint.
  # @return [PutBusinessServicePriorityThresholds200Response]
  describe 'put_business_service_priority_thresholds test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for remove_business_service_account_subscription
  # Delete Business Service Account Subscription
  # Unsubscribe your Account from a Business Service.  Scoped OAuth requires: &#x60;subscribers.write&#x60; 
  # @param accept The &#x60;Accept&#x60; header is used as a versioning header.
  # @param id The ID of the resource.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'remove_business_service_account_subscription test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for remove_business_service_notification_subscriber
  # Remove Business Service Subscribers
  # Unsubscribes the matching Subscribers from a Business Service.  Scoped OAuth requires: &#x60;subscribers.write&#x60; 
  # @param accept The &#x60;Accept&#x60; header is used as a versioning header.
  # @param id The ID of the resource.
  # @param [Hash] opts the optional parameters
  # @option opts [CreateBusinessServiceNotificationSubscribersRequest] :create_business_service_notification_subscribers_request The entities to unsubscribe.
  # @return [RemoveBusinessServiceNotificationSubscriber200Response]
  describe 'remove_business_service_notification_subscriber test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_business_service
  # Update a Business Service
  # Update an existing Business Service. NOTE that this endpoint also accepts the PATCH verb.  Business services model capabilities that span multiple technical services and that may be owned by several different teams.  For more information see the [API Concepts Document](../../api-reference/ZG9jOjI3NDc5Nzc-api-concepts#business-services)  Scoped OAuth requires: &#x60;services.write&#x60; 
  # @param accept The &#x60;Accept&#x60; header is used as a versioning header.
  # @param content_type 
  # @param id The ID of the resource.
  # @param [Hash] opts the optional parameters
  # @option opts [UpdateBusinessServiceRequest] :update_business_service_request 
  # @return [CreateBusinessService200Response]
  describe 'update_business_service test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
