=begin
#PagerDuty API

#This document describes the PagerDuty REST APIs.  For guides and examples please visit our [Documentation.](https://developer.pagerduty.com/docs/get-started/getting-started/)  Our REST APIs are defined in OpenAPI v3.x. You can view the schema at [github.com/PagerDuty/api-schema](https://github.com/PagerDuty/api-schema).  Note that properties in some schemas have fields not shown by default such as `readOnly`, `format`, and `default`. Hover your cursor over the right column that looks like `optional+1` to see the full list of fields. 

The version of the OpenAPI document: 2.0.0
Contact: support@pagerduty.com
Generated by: https://openapi-generator.tech
Generator version: 7.6.0

=end

require 'spec_helper'
require 'json'

# Unit tests for PagerDutyOpenapiClient::OnCallsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'OnCallsApi' do
  before do
    # run before each test
    @api_instance = PagerDutyOpenapiClient::OnCallsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OnCallsApi' do
    it 'should create an instance of OnCallsApi' do
      expect(@api_instance).to be_instance_of(PagerDutyOpenapiClient::OnCallsApi)
    end
  end

  # unit tests for list_on_calls
  # List all of the on-calls
  # List the on-call entries during a given time range.  An on-call represents a contiguous unit of time for which a User will be on call for a given Escalation Policy and Escalation Rules.  For more information see the [API Concepts Document](../../api-reference/ZG9jOjI3NDc5Nzc-api-concepts#on-calls)  Scoped OAuth requires: &#x60;oncalls.read&#x60;  This API operation has operation specific rate limits. See the [Rate Limits](https://developer.pagerduty.com/docs/72d3b724589e3-rest-api-rate-limits) page for more information. 
  # @param accept The &#x60;Accept&#x60; header is used as a versioning header.
  # @param content_type 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :time_zone Time zone in which results will be rendered. This will default to the account time zone.
  # @option opts [Integer] :limit The number of results per page.
  # @option opts [Integer] :offset Offset to start pagination search results.
  # @option opts [Boolean] :total By default the &#x60;total&#x60; field in pagination responses is set to &#x60;null&#x60; to provide the fastest possible response times. Set &#x60;total&#x60; to &#x60;true&#x60; for this field to be populated.  See our [Pagination Docs](https://developer.pagerduty.com/docs/rest-api-v2/pagination/) for more information. 
  # @option opts [String] :include Array of additional details to include.
  # @option opts [Array<String>] :user_ids Filters the results, showing only on-calls for the specified user IDs.
  # @option opts [Array<String>] :escalation_policy_ids Filters the results, showing only on-calls for the specified escalation policy IDs.
  # @option opts [Array<String>] :schedule_ids Filters the results, showing only on-calls for the specified schedule IDs. If &#x60;null&#x60; is provided in the array, it includes permanent on-calls due to direct user escalation targets.
  # @option opts [Time] :since The start of the time range over which you want to search. If an on-call period overlaps with the range, it will be included in the result. Defaults to current time. On-call shifts are limited to 90 days in the future.
  # @option opts [Time] :_until The end of the time range over which you want to search. If an on-call period overlaps with the range, it will be included in the result. Defaults to current time. On-call shifts are limited to 90 days in the future, and the &#x60;until&#x60; time cannot be before the &#x60;since&#x60; time.
  # @option opts [Boolean] :earliest This will filter on-calls such that only the earliest on-call for each combination of escalation policy, escalation level, and user is returned. This is useful for determining when the \&quot;next\&quot; on-calls are for a given set of filters.
  # @return [ListOnCalls200Response]
  describe 'list_on_calls test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
