=begin
#PagerDuty API

#This document describes the PagerDuty REST APIs.  For guides and examples please visit our [Documentation.](https://developer.pagerduty.com/docs/get-started/getting-started/)  Our REST APIs are defined in OpenAPI v3.x. You can view the schema at [github.com/PagerDuty/api-schema](https://github.com/PagerDuty/api-schema).  Note that properties in some schemas have fields not shown by default such as `readOnly`, `format`, and `default`. Hover your cursor over the right column that looks like `optional+1` to see the full list of fields. 

The version of the OpenAPI document: 2.0.0
Contact: support@pagerduty.com
Generated by: https://openapi-generator.tech
Generator version: 7.6.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for PagerDutyOpenapiClient::ValueByFieldID
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe PagerDutyOpenapiClient::ValueByFieldID do
  let(:instance) { PagerDutyOpenapiClient::ValueByFieldID.new }

  describe 'test an instance of ValueByFieldID' do
    it 'should create an instance of ValueByFieldID' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(PagerDutyOpenapiClient::ValueByFieldID)
    end
  end

  describe 'test attribute "id"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "value"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
